/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_samraksh_android_samplendk_MainActivity */

#ifndef _Included_com_samraksh_android_samplendk_MainActivity
#define _Included_com_samraksh_android_samplendk_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samraksh_android_samplendk_MainActivity
 * Method:    invokeNativeInitialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_samraksh_android_samplendk_MainActivity_invokeNativeInitialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
