//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;


//
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
//
namespace TestRig
{

    public class XmlUtil
    {
        private static char[] badChars = { '\r', '\n', '\t' };

        public static string FixBadXmlChars(string value) {
            return value.Trim(badChars);
        }

        public static string[] FixBadXmlChars(string[] value) {
            value[0].Trim(badChars);
            value[value.Length].Trim(badChars);
            return value;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class TestResults
    {

        private string testCompleteField;

        private string testResultField;

        private string testPassField;

        private string testDateTimeField;

        private string testDurationField;

        private string testAccuracyField;

        private string testReturnParameter1Field;

        private string testReturnParameter2Field;

        private string testReturnParameter3Field;

        private string testReturnParameter4Field;

        private string testReturnParameter5Field;

        private string testExecutionMachineField;

        private TestResultsTestDescriptionTest[] testDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestComplete {
            get {
                return this.testCompleteField;
            }
            set {
                this.testCompleteField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestResult {
            get {
                return this.testResultField;
            }
            set {
                this.testResultField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestPass {
            get {
                return this.testPassField;
            }
            set {
                this.testPassField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestDateTime {
            get {
                return this.testDateTimeField;
            }
            set {
                this.testDateTimeField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestDuration {
            get {
                return this.testDurationField;
            }
            set {
                this.testDurationField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestAccuracy {
            get {
                return this.testAccuracyField;
            }
            set {
                this.testAccuracyField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestReturnParameter1 {
            get {
                return this.testReturnParameter1Field;
            }
            set {
                this.testReturnParameter1Field = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestReturnParameter2 {
            get {
                return this.testReturnParameter2Field;
            }
            set {
                this.testReturnParameter2Field = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestReturnParameter3 {
            get {
                return this.testReturnParameter3Field;
            }
            set {
                this.testReturnParameter3Field = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestReturnParameter4 {
            get {
                return this.testReturnParameter4Field;
            }
            set {
                this.testReturnParameter4Field = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestReturnParameter5 {
            get {
                return this.testReturnParameter5Field;
            }
            set {
                this.testReturnParameter5Field = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestExecutionMachine {
            get {
                return this.testExecutionMachineField;
            }
            set {
                this.testExecutionMachineField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Test", typeof(TestResultsTestDescriptionTest), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public TestResultsTestDescriptionTest[] TestDescription {
            get {
                return this.testDescriptionField;
            }
            set {
                this.testDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class TestResultsTestDescriptionTest
    {

        private string descriptionField;

        private string testPathField;

        private string testProjNameField;

        private string testerNameField;

        private string testLocationField;

        private string testMFVersionNumField;

        private string testGitOptionField;

        private string testGitRevField;

        private string testGitBranchField;

        private string testUsePrecompiledBinaryField;

        private string testHardwareField;

        private string testSolutionField;

        private string testMemoryTypeField;

        private string testSolutionTypeField;

        private string testGCCVersionField;

        private string testSupportingField;

        private string testJTAGHarnessField;

        private string testPowerAutomateSelectedField;

        private string testBuildField;

        private string testTimeoutField;

        private string testUseLogicField;

        private string testSampleTimeMsField;

        private string testSampleFrequencyField;

        private string testUseScriptField;

        private string testScriptNameField;

        private string testScriptTimeoutMsField;

        private string testAnalysisField;

        private string testAnalysisScriptNameField;

        private string testUseResultsFileField;

        private string testResultsFileNameField;

        private string testUseCOMField;

        private string testForceCOMField;

        private string testCOMParametersField;

        private string testDelayField;

        private string nameField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestPath {
            get {
                return this.testPathField;
            }
            set {
                this.testPathField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestProjName {
            get {
                return this.testProjNameField;
            }
            set {
                this.testProjNameField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TesterName {
            get {
                return this.testerNameField;
            }
            set {
                this.testerNameField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestLocation {
            get {
                return this.testLocationField;
            }
            set {
                this.testLocationField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestMFVersionNum {
            get {
                return this.testMFVersionNumField;
            }
            set {
                this.testMFVersionNumField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestGitOption {
            get {
                return this.testGitOptionField;
            }
            set {
                this.testGitOptionField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestGitRev
        {
            get
            {
                return this.testGitRevField;
            }
            set
            {
                this.testGitRevField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestGitBranch {
            get {
                return this.testGitBranchField;
            }
            set {
                this.testGitBranchField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestUsePrecompiledBinary {
            get {
                return this.testUsePrecompiledBinaryField;
            }
            set {
                this.testUsePrecompiledBinaryField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestHardware {
            get {
                return this.testHardwareField;
            }
            set {
                this.testHardwareField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestSolution {
            get {
                return this.testSolutionField;
            }
            set {
                this.testSolutionField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestMemoryType {
            get {
                return this.testMemoryTypeField;
            }
            set {
                this.testMemoryTypeField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestSolutionType {
            get {
                return this.testSolutionTypeField;
            }
            set {
                this.testSolutionTypeField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestGCCVersion {
            get {
                return this.testGCCVersionField;
            }
            set {
                this.testGCCVersionField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestSupporting {
            get {
                return this.testSupportingField;
            }
            set {
                this.testSupportingField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestJTAGHarness {
            get {
                return this.testJTAGHarnessField;
            }
            set {
                this.testJTAGHarnessField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestPowerAutomateSelected {
            get {
                return this.testPowerAutomateSelectedField;
            }
            set {
                this.testPowerAutomateSelectedField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestBuild {
            get {
                return this.testBuildField;
            }
            set {
                this.testBuildField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestTimeout {
            get {
                return this.testTimeoutField;
            }
            set {
                this.testTimeoutField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestUseLogic {
            get {
                return this.testUseLogicField;
            }
            set {
                this.testUseLogicField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestSampleTimeMs {
            get {
                return this.testSampleTimeMsField;
            }
            set {
                this.testSampleTimeMsField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestSampleFrequency {
            get {
                return this.testSampleFrequencyField;
            }
            set {
                this.testSampleFrequencyField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string testUseScript {
            get {
                return this.testUseScriptField;
            }
            set {
                this.testUseScriptField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string testScriptName {
            get {
                return this.testScriptNameField;
            }
            set {
                this.testScriptNameField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string testScriptTimeoutMs {
            get {
                return this.testScriptTimeoutMsField;
            }
            set {
                this.testScriptTimeoutMsField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestAnalysis {
            get {
                return this.testAnalysisField;
            }
            set {
                this.testAnalysisField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestAnalysisScriptName {
            get {
                return this.testAnalysisScriptNameField;
            }
            set {
                this.testAnalysisScriptNameField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestUseResultsFile {
            get {
                return this.testUseResultsFileField;
            }
            set {
                this.testUseResultsFileField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestResultsFileName {
            get {
                return this.testResultsFileNameField;
            }
            set {
                this.testResultsFileNameField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestUseCOM {
            get {
                return this.testUseCOMField;
            }
            set {
                this.testUseCOMField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestForceCOM {
            get {
                return this.testForceCOMField;
            }
            set {
                this.testForceCOMField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestCOMParameters {
            get {
                return this.testCOMParametersField;
            }
            set {
                this.testCOMParametersField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TestDelay {
            get {
                return this.testDelayField;
            }
            set {
                this.testDelayField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = XmlUtil.FixBadXmlChars(value);
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = XmlUtil.FixBadXmlChars(value);
            }
        }
    }

    // Requires using System.Collections.ObjectModel;
    public class TestResultss : System.Collections.ObjectModel.ObservableCollection<TestResults>
    {
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private TestResults[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TestResults")]
        public TestResults[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}