//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRig.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("interface\\olimex-arm-usb-tiny-h.cfg")]
        public string OCDInterface {
            get {
                return ((string)(this["OCDInterface"]));
            }
            set {
                this["OCDInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("target\\stm32xl.cfg")]
        public string OCDTarget {
            get {
                return ((string)(this["OCDTarget"]));
            }
            set {
                this["OCDTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\SamTest\\openocd-bin\\openocd.exe")]
        public string OCDExe {
            get {
                return ((string)(this["OCDExe"]));
            }
            set {
                this["OCDExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\SamTest\\codesourcery")]
        public string CSPath {
            get {
                return ((string)(this["CSPath"]));
            }
            set {
                this["CSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\MicroFrameworkPK_v4_0")]
        public string MFPath {
            get {
                return ((string)(this["MFPath"]));
            }
            set {
                this["MFPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\SamTest")]
        public string TTPath {
            get {
                return ((string)(this["TTPath"]));
            }
            set {
                this["TTPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test")]
        public string TSPath {
            get {
                return ((string)(this["TSPath"]));
            }
            set {
                this["TSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Users\\Chris\\AppData\\Local\\GitHub\\PortableGit_8810fd5c2c79c73adcc73fd0825f3b32f" +
            "db816e7")]
        public string GHPath {
            get {
                return ((string)(this["GHPath"]));
            }
            set {
                this["GHPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test\\Receipts")]
        public string TRPath {
            get {
                return ((string)(this["TRPath"]));
            }
            set {
                this["TRPath"] = value;
            }
        }
    }
}
