//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestRig.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\DotNet-MF\\MicroFrameworkPK_v4_0")]
        public string MFPath_4_0 {
            get {
                return ((string)(this["MFPath_4_0"]));
            }
            set {
                this["MFPath_4_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Test\\Receipts")]
        public string TRPath {
            get {
                return ((string)(this["TRPath"]));
            }
            set {
                this["TRPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\DotNet-MF\\MicroFrameworkPK_v4_3")]
        public string MFPath_4_3 {
            get {
                return ((string)(this["MFPath_4_3"]));
            }
            set {
                this["MFPath_4_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MFSelection {
            get {
                return ((int)(this["MFSelection"]));
            }
            set {
                this["MFSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HSSelection {
            get {
                return ((int)(this["HSSelection"]));
            }
            set {
                this["HSSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MTSelection {
            get {
                return ((int)(this["MTSelection"]));
            }
            set {
                this["MTSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int STSelection {
            get {
                return ((int)(this["STSelection"]));
            }
            set {
                this["STSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GVSelection {
            get {
                return ((int)(this["GVSelection"]));
            }
            set {
                this["GVSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MFPathSelection {
            get {
                return ((int)(this["MFPathSelection"]));
            }
            set {
                this["MFPathSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMPortPrimary {
            get {
                return ((int)(this["COMPortPrimary"]));
            }
            set {
                this["COMPortPrimary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSystem\\openocd-0.7.0\\scripts\\interface\\olimex-arm-usb-tiny-h.cfg")]
        public string OCDInterfacePrimary {
            get {
                return ((string)(this["OCDInterfacePrimary"]));
            }
            set {
                this["OCDInterfacePrimary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSystem\\openocd-0.7.0\\scripts\\target\\stm32xl.cfg")]
        public string OCDTarget {
            get {
                return ((string)(this["OCDTarget"]));
            }
            set {
                this["OCDTarget"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSystem\\openocd-0.7.0\\bin-x64\\openocd-x64-0.7.0.exe")]
        public string OCDExe {
            get {
                return ((string)(this["OCDExe"]));
            }
            set {
                this["OCDExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSystem")]
        public string CSPath {
            get {
                return ((string)(this["CSPath"]));
            }
            set {
                this["CSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSystem\\Automated Testing Software\\GitBin")]
        public string GitPath {
            get {
                return ((string)(this["GitPath"]));
            }
            set {
                this["GitPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSuite")]
        public string TSPath {
            get {
                return ((string)(this["TSPath"]));
            }
            set {
                this["TSPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSystem\\openocd-bin\\interface\\olimex-arm-usb-ocd.cfg")]
        public string OCDInterfaceSecondary1 {
            get {
                return ((string)(this["OCDInterfaceSecondary1"]));
            }
            set {
                this["OCDInterfaceSecondary1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMPortSecondary1 {
            get {
                return ((int)(this["COMPortSecondary1"]));
            }
            set {
                this["COMPortSecondary1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PowerCycleAutomated {
            get {
                return ((bool)(this["PowerCycleAutomated"]));
            }
            set {
                this["PowerCycleAutomated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32001")]
        public int ServerListenPort {
            get {
                return ((int)(this["ServerListenPort"]));
            }
            set {
                this["ServerListenPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45123")]
        public string ServerKey {
            get {
                return ((string)(this["ServerKey"]));
            }
            set {
                this["ServerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string ServerAddress {
            get {
                return ((string)(this["ServerAddress"]));
            }
            set {
                this["ServerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32001")]
        public int ServerPort {
            get {
                return ((int)(this["ServerPort"]));
            }
            set {
                this["ServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45123")]
        public string ClientServerKey {
            get {
                return ((string)(this["ClientServerKey"]));
            }
            set {
                this["ClientServerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtpout.secureserver.net")]
        public string NotifyHost {
            get {
                return ((string)(this["NotifyHost"]));
            }
            set {
                this["NotifyHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testrig-noreply@samraksh.com")]
        public string NotifySender {
            get {
                return ((string)(this["NotifySender"]));
            }
            set {
                this["NotifySender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N2!Erbxs")]
        public string NotifyPassword {
            get {
                return ((string)(this["NotifyPassword"]));
            }
            set {
                this["NotifyPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("testrig-noreply@samraksh.com")]
        public string NotifyUser {
            get {
                return ((string)(this["NotifyUser"]));
            }
            set {
                this["NotifyUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("your_name@samraksh.com")]
        public string NotifyReceipts {
            get {
                return ((string)(this["NotifyReceipts"]));
            }
            set {
                this["NotifyReceipts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EmailCB {
            get {
                return ((bool)(this["EmailCB"]));
            }
            set {
                this["EmailCB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Work\\TestSystem\\openocd-bin\\interface\\olimex-arm-usb-ocd-h.cfg")]
        public string OCDInterfaceSecondary2 {
            get {
                return ((string)(this["OCDInterfaceSecondary2"]));
            }
            set {
                this["OCDInterfaceSecondary2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int COMPortSecondary2 {
            get {
                return ((int)(this["COMPortSecondary2"]));
            }
            set {
                this["COMPortSecondary2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1480")]
        public string RadioIDPrimary {
            get {
                return ((string)(this["RadioIDPrimary"]));
            }
            set {
                this["RadioIDPrimary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7110")]
        public string RadioIDSecondary1 {
            get {
                return ((string)(this["RadioIDSecondary1"]));
            }
            set {
                this["RadioIDSecondary1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14330")]
        public string RadioIDSecondary2 {
            get {
                return ((string)(this["RadioIDSecondary2"]));
            }
            set {
                this["RadioIDSecondary2"] = value;
            }
        }
    }
}
